# Generated by Django 2.2 on 2019-04-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='primary_goals',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='nominator',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='votes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='event_rating',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='primary_goals',
            field=models.TextField(null=True),
        ),
    ]
