# Generated by Django 2.2 on 2019-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190409_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tag name (e.g. Diversity).', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date', 'event_name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='conference_contact',
            field=models.EmailField(help_text='Enter email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='nominator',
            field=models.EmailField(help_text='Enter email address.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='event_rating',
            field=models.CharField(help_text='Enter text.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('p', 'Proposed'), ('a', 'Accepted'), ('d', 'Done')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tag for this event.', to='events.Tag'),
        ),
    ]
