# Generated by Django 2.2 on 2019-04-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190409_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tag',
            new_name='tags',
        ),
    ]
