# Generated by Django 2.2 on 2019-04-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190409_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_title',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.Event'),
            preserve_default=False,
        ),
    ]
