# Generated by Django 2.2 on 2019-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190411_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sponsored',
            field=models.CharField(choices=[('Y', 'Yes'), ('P', 'Probably'), ('M', 'Maybe'), ('N', 'No')], default='M', max_length=1),
        ),
    ]
