# Generated by Django 2.2 on 2019-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190412_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cfp_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='conference_contact',
            field=models.EmailField(blank=True, help_text='Enter email address.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='nominator',
            field=models.EmailField(blank=True, help_text='Enter email address.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select a tag for this event.', null=True, to='events.Tag'),
        ),
    ]
