# Generated by Django 2.2 on 2019-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190412_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select a tag for this event.', to='events.Tag'),
        ),
    ]
