# Generated by Django 2.2 on 2019-04-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20190412_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='followup_w_nominee',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsored_before',
            field=models.BooleanField(null=True),
        ),
    ]
