# Generated by Django 2.2 on 2019-04-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20190414_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='followup_w_nominee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsored_before',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
